### ISSUE TITLE
this.Parameter is detected as undefined

### ISSUE THREAD

**Issue by vamsystem** [fusetools/hikr#1]
I am using Fuse v. 0.22.0. I was trying to run this example and I got this error:

LOG: InternalError: Script error: Name: TypeError: Cannot read property 'map' of undefined
    Error message: Uncaught TypeError: Cannot read property 'map' of undefined
    File name: Pages/EditHikePage.js
    Line number: 5
    Source line: var name = hike.map(function(x) { return x.name; });
    JS stack trace: TypeError: Cannot read property 'map' of undefined
        at null._moduleFunc (Pages/EditHikePage.js:5:16)
    <C:\ProgramData\Uno\Packages\Fuse.Scripting.V8\0.32.11\$.uno:135>
LOG: Error: JavaScript error in Pages/EditHikePage.js line 5. Uncaught TypeError: Cannot read property 'map' of undefined in Fuse.Reactive.JavaScript<C:\ProgramData\Uno\Packages\Fuse.Reactive\0.32.11\$.uno:1354>

**Comment by yupferris** [comment]
Hi there, `this.Parameter` was introduced in Fuse 0.24. I recommend upgrading to the latest version (0.25).

**Comment by vamsystem** [comment]
I see, thanks for reply

**Comment by yupferris** [comment]
np!

**Comment by vamsystem** [comment]
Hello again! I've updated to version 0.25.5 and I have another problem with this.Parameter, now I've changed some code lines. The problem is that I can't retrieve custom parameters that I've passed to the router. Please tell me what am I doing wrong. These are my changes:

 **File: HomePage.js**

```
...
function goToHike(arg) {
    console.log('Selected index: ' + Context.hikes.indexOf(arg.data)); // This return the index successfully

    var params = { "index": Context.hikes.indexOf(arg.data) };

    router.push("editHike", params);
}
...
```

**File: EditHikePage.js**

```
var Context = require("Modules/Context");
var Observable = require("FuseJS/Observable");

var params = this.Parameter;
var hike = Observable(Context.hikes.getAt(params.value.index));
...
```

**Comment by yupferris** [comment]
Please ask this question on our [slack channel](https://slackcommunity.fusetools.com/) or our [forums](https://www.fusetools.com/community/forums), as this is not an issue with the code provided in this repo.
