### ISSUE TITLE
No data passing to another router member

### ISSUE THREAD

**Issue by affibox** [fusetools/hikr#5]
I've try many times to pass data using this method and nothing seems to be happening. I only get an observable with no value on it

**Comment by eksperts** [comment]
Gave this a thorough test, and all of my router-related changes to `goToHike()` function were happening exactly as expected. I could pass over a whole hike object or just a hike id, as I felt necessary. `this.Parameter` on the receiving end was changing as expected, too.

If the issue persists, I suggest making a forum post instead: https://www.fusetools.com/community/forums/threads/new

I suggest closing this issue.

**Comment by kristianhasselknippe** [comment]
closing this based on @eksperts suggestion
